#!/usr/bin/env node
// prove.mjs — run a question battery through the REAL retrieval engine and emit an auditable
// proof artifact. It calls searchAll() directly — the *exact* function the search_ruvnet MCP tool
// wraps — so the scores are the same ones a live Claude session sees, just without the JSON-RPC
// envelope. Models load once for the whole battery.
//
//   KB_MODEL_CACHE=/path/to/models-cache node scripts/prove.mjs
//   [--questions scripts/proof-questions.json] [--k 3]
//
// Writes:  PROOF.md (human table + summary)  and  data/proof-results.json (machine-readable)
// Exit 0 if every question resolves to an expected repo at/above its threshold; 1 otherwise.
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { searchAll } from '../kb/forge-ask-all.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const KB = path.join(ROOT, 'kb');
const arg = (f, d) => { const i = process.argv.indexOf(f); return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : d; };
const QFILE = path.resolve(arg('--questions', path.join(ROOT, 'scripts', 'proof-questions.json')));
const K = parseInt(arg('--k', '3'), 10);
const OUTBASE = arg('--out', 'PROOF'); // PROOF.md + data/<lower>-results.json

const questions = JSON.parse(fs.readFileSync(QFILE, 'utf8'));
const started = new Date().toISOString();
console.log(`[prove] ${questions.length} questions · k=${K} · brain=${KB}\n`);

const results = [];
for (let i = 0; i < questions.length; i++) {
  const q = questions[i];
  let ranked = [];
  try { const out = await searchAll({ dir: KB, query: q.query, k: K, pool: 8 }); ranked = out?.results || []; }
  catch (e) { console.log(`ERR   #${i + 1}  ${e.message}`); }
  const top = ranked[0] || null;
  const got = top?.repo ?? null;
  const eff = (got === 'concepts' && top?.path) ? (top.path.split('/')[0] || got) : got; // primer's home repo
  const score = top?.ceScore ?? null;
  const citedPath = top ? `${top.repo}/${top.path}` : null;
  const exp = q.expectRepo;
  const repoOk = !exp || (Array.isArray(exp) ? (exp.includes(got) || exp.includes(eff)) : (got === exp || eff === exp));
  const relOk = score == null ? true : score >= (q.minRelevance ?? -3);
  const pass = !!got && repoOk && relOk;
  results.push({ n: i + 1, set: q.set || '', query: q.query, expect: exp, got, eff, score, citedPath, pass });
  const s = score == null ? 'n/a' : score.toFixed(3);
  console.log(`${pass ? 'PASS' : 'FAIL'}  #${String(i + 1).padStart(2)}  ${(eff || '(no hit)').padEnd(24)} @ ${String(s).padStart(7)}  ${q.query.slice(0, 64)}`);
}

const passed = results.filter((r) => r.pass).length;
const scored = results.filter((r) => r.score != null).map((r) => r.score).sort((a, b) => a - b);
const median = scored.length ? scored[Math.floor(scored.length / 2)] : null;
const bySet = {};
for (const r of results) { const k = r.set || 'other'; (bySet[k] ??= { pass: 0, total: 0 }); bySet[k].total++; if (r.pass) bySet[k].pass++; }

// machine artifact
fs.mkdirSync(path.join(ROOT, 'data'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'data', `${OUTBASE.toLowerCase()}-results.json`),
  JSON.stringify({ started, finished: new Date().toISOString(), k: K, passed, total: results.length, bySet, results }, null, 2));

// human artifact
const esc = (s) => String(s).replace(/\|/g, '\\|');
const setLines = Object.entries(bySet).map(([k, v]) => `| ${k} | ${v.pass}/${v.total} |`).join('\n');
const rows = results.map((r) => `| ${r.n} | ${r.set} | ${esc(r.query)} | ${r.eff || '—'} | ${r.score == null ? 'n/a' : r.score.toFixed(3)} | ${esc(r.citedPath || '—')} | ${r.pass ? '✅' : '❌'} |`).join('\n');
const md = `# RuvNet Brain — Proof of Retrieval (live run)

> Generated by \`node scripts/prove.mjs\` on ${started}. Re-run it yourself; this file is the output, not a claim.
> Each row is a real query through \`searchAll()\` — the exact engine the \`search_ruvnet\` MCP tool wraps.

## Headline

**${passed}/${results.length} questions resolved to an expected repo** at/above threshold. Median top-hit relevance: **${median == null ? 'n/a' : median.toFixed(3)}**.

| Question set | Passed |
|---|---|
${setLines}

- **tuned / held-out** — the capability-confidence gate (held-out built *after* tuning ⇒ not overfit).
- **anti-drift** — questions phrased the way a skeptic would, where Claude normally reaches for pgvector/Pinecone or doubts a real tool.
- **adversarial** — negative-framed ("I heard it *can't*…") to prove the brain doesn't fold.
- **implementation / coverage / cross-repo** — depth and breadth across all 19 repos.

## Every question, every score

| # | set | question | resolved repo | relevance | cited source | ok |
|--:|---|---|---|--:|---|:--:|
${rows}

> "relevance" is the cross-encoder score after name-affinity boost; higher is sharper. Negative is normal for
> a cross-encoder and still ranks correctly — what matters for the *never-wrongly-doubt* guarantee is that the
> top hit lands on the right repo with a cited file you can open.
`;
fs.writeFileSync(path.join(ROOT, `${OUTBASE}.md`), md);

console.log(`\n[prove] ${passed}/${results.length} passed · median ${median == null ? 'n/a' : median.toFixed(3)}`);
console.log('[prove] wrote PROOF.md + data/proof-results.json');
process.exit(passed === results.length ? 0 : 1);
